@startuml Sprint2_Montres_ecommerce
left to right direction
actor Client
actor Administrateur

rectangle "Sprint 2" {
  usecase "Paiement" as UC_Checkout
  usecase "Laisser un avis" as UC_Review
  usecase "Gérer les utilisateurs" as UC_ManageUsers
}

Client -- UC_Checkout
Client -- UC_Review
Administrateur -- UC_ManageUsers
@enduml
