@startuml
package Pkg_Admin {
    usecase "Ajouter un produit" as UC1
    usecase "Modifier un produit" as UC2
    usecase "Supprimer un produit" as UC3
    usecase "Gérer les commandes" as UC4
    usecase "Gérer les utilisateurs" as UC5
}

actor Administrateur

left to right direction
Administrateur -- UC1
Administrateur -- UC2
Administrateur -- UC3
Administrateur -- UC4
Administrateur -- UC5

@enduml
